### ISSUE TITLE
Error with Yaml constant

### ISSUE THREAD

**Issue by antonioolmedo** [EasyCorp/easy-log-handler#19]
Hello there, 

I got the error below when I installed this package on version v1.0.7 which uses YAML 2.3 but that class hasn't constant `DUMP_OBJECT`.

[Yaml package v2.3.42 ](https://github.com/symfony/yaml/blob/v2.3.42/Yaml.php)

> PHP Fatal error:  Undefined class constant 'DUMP_OBJECT' in /var/www/oferplan-front/vendor/easycorp/easy-log-handler/src/EasyLogFormatter.php on line 369

I solved it installing v.1.0.4, I think the Formatter change occurs in this [commit](https://github.com/EasyCorp/easy-log-handler/commit/21c442f5d08b6761a6fa7653e08a5525fb4ccd2b).

Thanks, Antonio.

**Comment by xabbuh** [comment]
I think the proper fix would be to bump the required version of the Yaml component.

**Comment by javiereguiluz** [comment]
This was finally fixed in the latest [1.0.9 version](https://github.com/EasyCorp/easy-log-handler/releases/tag/v1.0.9).
