### ISSUE TITLE
Fatal error: serialization of 'closure' is not allowed on custom context objects

### ISSUE THREAD

**Issue by andrew-demb** [EasyCorp/easy-log-handler#21]
I got an error on log records with context objects with some internal callables in properties.
My objects implements `\JsonSerializable` interface, so I don't expect this error.

Reproduction script: https://github.com/andrew-demb/easy-log-handler-bug-serialize-closure

**Comment by javiereguiluz** [comment]
I'm closing this issue because this package is now abandoned. Thanks!
