### ISSUE TITLE
Buffered handler and messenger long running process

### ISSUE THREAD

**Issue by B-Galati** [EasyCorp/easy-log-handler#24]
Hello and thank you for this beautiful handler :-)

In the doc it is advised to define a buffered handler in monolog config but I think this sort of handler is tricky to use for long running process such as Messenger worker no?

I did not try it yes I am considering a solution that would involved having a custom middleware that would flush all Resetable monolog Logger found in the container.

WDYT? Am I missing something?

**Comment by Koc** [comment]
Indeed, buffered handler causes memory leaks during long running processes. For example when I try to perform reindex through [FOSElasticaBundle](https://github.com/FriendsOfSymfony/FOSElasticaBundle).

Here [Blackfire comparison](https://blackfire.io/profiles/compare/3a4aaf7e-9fc0-4448-be0d-e0dcf29a8f48...c7a29172-c292-40e8-92b1-68533ad8229c/graph?settings%5Bdimension%5D=pmu&settings%5Bdisplay%5D=landscape&settings%5BtabPane%5D=nodes&selected=&callname=main()) for 2 indexer calls: for 4000 and 5000 records. As you see - memory increased by 85mb for each 1000 records.

The workaround that I used:

```php
    private function flushBufferedHandlers(): void
    {
        if (!$this->logger instanceof Logger) { // Monolog
            return;
        }

        foreach ($this->logger->getHandlers() as $handler) {
            if ($handler instanceof BufferHandler) {
                $handler->flush();
            }
        }
    }
```

And [Blackfire profiles](https://blackfire.io/profiles/compare/c7a29172-c292-40e8-92b1-68533ad8229c...85045e9c-5f61-44ec-aa2e-e5c516c4bb72/graph?settings%5Bdimension%5D=pmu&settings%5Bdisplay%5D=landscape&settings%5BtabPane%5D=nodes&selected=&callname=main()) comparison to the previous run. The only drawback: it is 25% slower. But memory usage is constant.

@javiereguiluz WDYT? What the recommended way to deal with long runnung process? Can you add suggestions to the documentation?

**Comment by Koc** [comment]
Maybe better way is to configure `$bufferSize` and `$flushOnOverflow` for the `BufferHandler`?

**Comment by B-Galati** [comment]
For production I did something simpler [here](https://github.com/B-Galati/monolog-sentry-handler/blob/master/doc/guide-symfony.md#step-4-flush-monolog-on-each-handled-symfony-messenger-message) for Messenger.

> Maybe better way is to configure `$bufferSize` and `$flushOnOverflow` for the `BufferHandler`?

It sounds like a good idea for dev!

**Comment by javiereguiluz** [comment]
I'm closing this issue because this package is now abandoned. Thanks!
